export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_SUCCEED = 'LOGIN_USER_SUCCEED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const CURRENT_USER_REQUESTED = 'CURRENT_USER_REQUESTED';

export const REGISTER_USER_REQUESTED = 'REGISTER_USER_REQUESTED';
export const REGISTER_USER_SUCCEED = 'REGISTER_USER_SUCCEED';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT_USER_REQUESTED = 'LOGOUT_USER_REQUESTED';
export const LOGOUT_USER_SUCCEED = 'LOGOUT_USER_SUCCEED';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';

export const SINGLE_USER_REQUESTED = 'SINGLE_USER_REQUESTED';
export const SINGLE_USER_SUCCEED = 'SINGLE_USER_SUCCEED';
export const SINGLE_USER_FAILED = 'SINGLE_USER_FAILED';

export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED';
export const UPDATE_USER_SUCCEED = 'UPDATE_USER_SUCCEED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const LIST_PRODUCT_REQUESTED = 'LIST_PRODUCT_REQUESTED';
export const LIST_PRODUCT_SUCCEED = 'LIST_PRODUCT_SUCCEED';
export const LIST_PRODUCT_FAILED = 'LIST_PRODUCT_FAILED';

export const LIST_POST_TAG_REQUESTED = 'LIST_POST_TAG_REQUESTED';
export const LIST_POST_TAG_SUCCEED = 'LIST_POST_TAG_SUCCEED';
export const LIST_POST_TAG_FAILED = 'LIST_POST_TAG_FAILED';

export const LIST_PRODUCT_CATEGORY_REQUESTED = 'LIST_PRODUCT_CATEGORY_REQUESTED';
export const LIST_PRODUCT_CATEGORY_SUCCEED = 'LIST_PRODUCT_CATEGORY_SUCCEED';
export const LIST_PRODUCT_CATEGORY_FAILED = 'LIST_PRODUCT_CATEGORY_FAILED';

export const LIST_POST_FAVORITED_REQUESTED = 'LIST_POST_FAVORITED_REQUESTED';
export const LIST_POST_FAVORITED_SUCCEED = 'LIST_POST_FAVORITED_SUCCEED';
export const LIST_POST_FAVORITED_FAILED = 'LIST_POST_FAVORITED_FAILED';

export const SINGLE_PRODUCT_REQUESTED = 'SINGLE_PRODUCT_REQUESTED';
export const SINGLE_PRODUCT_SUCCEED = 'SINGLE_PRODUCT_SUCCEED';
export const SINGLE_PRODUCT_FAILED = 'SINGLE_PRODUCT_FAILED';

export const LIST_TAG_REQUESTED = 'LIST_TAG_REQUESTED';
export const LIST_TAG_SUCCEED = 'LIST_TAG_SUCCEED';
export const LIST_TAG_FAILED = 'LIST_TAG_FAILED';

export const LIST_CATEGORY_REQUESTED = 'LIST_CATEGORY_REQUESTED';
export const LIST_CATEGORY_SUCCEED = 'LIST_CATEGORY_SUCCEED';
export const LIST_CATEGORY_FAILED = 'LIST_CATEGORY_FAILED';

export const LIST_BRAND_REQUESTED = 'LIST_BRAND_REQUESTED';
export const LIST_BRAND_SUCCEED = 'LIST_BRAND_SUCCEED';
export const LIST_BRAND_FAILED = 'LIST_BRAND_FAILED';

export const LIST_COMMENT_REQUESTED = 'LIST_COMMENT_REQUESTED';
export const LIST_COMMENT_SUCCEED = 'LIST_COMMENT_SUCCEED';
export const LIST_COMMENT_FAILED = 'LIST_COMMENT_FAILED';

export const LIST_CART_REQUESTED = 'LIST_CART_REQUESTED';
export const LIST_CART_SUCCEED = 'LIST_CART_SUCCEED';
export const LIST_CART_FAILED = 'LIST_CART_FAILED';

export const ADD_TO_CART_REQUESTED = 'ADD_TO_CART_REQUESTED';
export const ADD_TO_CART_SUCCEED = 'ADD_TO_CART_SUCCEED';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';

export const ORDER_REQUESTED = 'ORDER_REQUESTED';
export const ORDER_SUCCEED = 'ORDER_SUCCEED';
export const ORDER_FAILED = 'ORDER_FAILED';
